name: 'mingo-production'

services:
  database:
    image: mysql:9.2.0
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u$MYSQL_USER',
          '-p$MYSQL_PASSWORD',
        ]
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
  api:
    image: teddyagt/mingo-server:latest
    restart: always
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
  migrations:
    image: teddyagt/mingo-migrations:latest
    restart: no
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
  web:
    image: teddyagt/mingo-client:latest
    restart: no
    volumes:
      - web-client-build:/app

volumes:
  web-client-build:
